# Generated by Django 2.2 on 2019-04-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Platforma',
            },
        ),
    ]
